name: Build and publish container

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Build and publish container

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive --prod
      - name: Build and publish container
        run: npx nx build-container api
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
